name: relief_sphere
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  provider: ^6.1.2
  go_router: ^14.6.2
  connectivity_plus: ^6.1.1
  shared_preferences: ^2.3.5
  logger: ^2.5.0
  flex_color_scheme: ^8.1.0
  json_annotation: ^4.9.0
  equatable: ^2.0.7
  appwrite: ^13.1.1
  uuid: ^4.5.1
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  json_serializable: ^6.9.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/audio/
    - assets/fonts/
