name: relief_sphere
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  provider: ^6.1.2
  go_router: ^14.6.2
  connectivity_plus: ^6.1.1
  shared_preferences: ^2.3.5
  logger: ^2.5.0
  flex_color_scheme: ^8.1.0
  json_annotation: ^4.9.0
  equatable: ^2.0.7
  uuid: ^4.5.1
  flutter_dotenv: ^5.2.1
  flutter_svg: ^2.0.17
  supabase_flutter: ^2.8.3
  flutter_secure_storage: ^9.2.4
  image_picker: ^1.1.2
  google_maps_flutter: ^2.10.0
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  timeline_tile: ^2.0.0
  google_nav_bar: ^5.0.7
  fl_chart: ^0.70.2
  dotlottie_loader: ^0.0.4
  lottie: ^3.3.0
  permission_handler: ^11.3.1
  timeago: ^3.7.0
  intl: ^0.18.0
  carousel_slider: ^5.0.0
  url_launcher: ^6.1.14
  khalti_checkout_flutter: ^1.0.0-dev.7
  firebase_core: ^3.11.0
  firebase_messaging: ^15.2.2
  flutter_local_notifications: ^18.0.1
  flutter_stripe: ^11.4.0
  http: ^1.1.0

dependency_overrides:
  web: ^0.4.0
  archive: ^3.3.5 # Add specific version for archive
  lottie: ^3.3.0 # Pin lottie version
  geolocator_web: ^4.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  json_serializable: ^6.9.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/audio/
    - assets/fonts/
    - assets/icons/
    - assets/lottie/
    - .env
